@SETLOCAL

@SET INPUT=LOREM_IPSUM.iso

MountIso -v -m %INPUT%
@SET ISODRVLETTER=%=ExitCodeAscii%

@IF "%ISODRVLETTER%" == "" @GOTO :END
@SET ISODRIVE=%ISODRVLETTER%:\

@ECHO.
@ECHO The ISO file %INPUT% has been mounted to drive %ISODRVLETTER%
@ECHO.
DIR %ISODRIVE%

@ECHO.
@ECHO.
@ECHO Ready to Dismount ISO file
@PAUSE

MountIso -d %INPUT%

:END
@ENDLOCAL
